name: Backend CI

on:
  push:
    branches:
      - main  # Trigger CI on pushes to the main branch

jobs:
  test:
    name: Run Tests
    runs-on: self-hosted

    strategy:
      matrix:
        node-version: [22] # Test on multiple Node.js versions

    environment: MONGO_URI

    steps:
    - name: Checkout Code
      uses: actions/checkout@v3

    # Set up Node.js
    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}

    # 打印环境变量（调试用，可删）
    - name: Print Env Secret
      env:
        MONGO_URI: ${{ secrets.MONGO_URI }}
        JWT_SECRET: ${{ secrets.JWT_SECRET }}
        PORT: ${{ secrets.PORT }}
      run: | 
        echo "MONGO_URI is: $MONGO_URI"
        echo "JWT_SECRET is: $JWT_SECRET"
        echo "PORT is: $PORT"

    # 停止已有 PM2 进程（忽略失败）
    - name: Run pm2 stop all
      run: pm2 stop all || true

    # 安装 Backend 依赖
    - name: Install Backend Dependencies
      working-directory: ./backend
      run: | 
        npm install --global yarn
        yarn install

    # 安装 Frontend 依赖并构建
    - name: Install Frontend Dependencies
      working-directory: ./frontend
      run: |
        sudo rm -rf ./build
        yarn install
        yarn run build

    # 创建 .env 文件
    - name: Create .env file
      working-directory: ./backend
      run: |
        echo "MONGO_URI=${{ secrets.MONGO_URI }}" >> .env
        echo "JWT_SECRET=${{ secrets.JWT_SECRET }}" >> .env
        echo "PORT=${{ secrets.PORT }}" >> .env

    # 运行 Backend 测试
    - name: Run Backend Tests
      env:
        MONGO_URI: ${{ secrets.MONGO_URI }}
        JWT_SECRET: ${{ secrets.JWT_SECRET }}
        PORT: ${{ secrets.PORT }}
      working-directory: ./backend
      run: npm test

    # 启动 Backend
    - name: Start backend with PM2
      run: |
        cd backend
        pm2 start server.js --name backend || true

    # 重启 PM2（可选）
    - run: pm2 restart all || true
